services:
  todoist-reminders-daemon:
    image: yashpatel21/todoist-reminders-daemon:1.0.1
    container_name: todoist-reminders-daemon
    restart: unless-stopped
    environment:
      TODOIST_API_TOKEN: ${TODOIST_API_TOKEN}
